### ISSUE TITLE
Implementazione Client

### ISSUE THREAD

**Issue by irenedg** [irenedg/CRUD-one#6]

**Comment by AulicinoDiego** [comment]
Risolto parzialmente con Commit : ae2dddfbb52d64f0ede032e6a4ba567d095d48af

**Comment by irenedg** [comment]
commit: d6bfbcd1d0fea7f4dfe5ec261826e26d2377922e

**Comment by RobertaConti-Jarvis** [comment]
commit: 1ca4bb0176fa07a294cae2639f6764569abab1bb

**Comment by AulicinoDiego** [comment]
corretti errori e completato implementazione con Commit : f5a2e82781202a33f9a04255c47336f05b354ca5
